name: Deploy to S3 and CloudFront

on:
  push:
    branches:
      - main  # Or 'master', whichever branch you use

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.1' # Use the version you use (check with node -v)

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build
        env:
          # Put your environment variables here if they are not in .env
          VITE_API_URL: https://d2m00zvvxio8.cloudfront.net 

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 # CHANGE THIS if your bucket is not in Mumbai

      - name: Deploy to S3
        # Replace 'unseenpricebucket' with your ACTUAL bucket name
        run: aws s3 sync dist/ s3://unseenprice-frontend --delete

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/*"